### ISSUE TITLE
GPL License 

### ISSUE THREAD

**Issue by tvandera** [skulumani/fdcl-hdf5#10]
Hello,

I'd like to use your library, but it's marked GPL. Can you make it LGPL (or MIT or BSD), such that we can link our program without effectively turning our program into a GPL one...

Thanks,
Tom

**Comment by skulumani** [comment]
Sure, I'll modify it tonight.

**Comment by skulumani** [comment]
Hi, just modified it to MIT.

https://github.com/skulumani/fdcl-hdf5

If you end up using it I'd love to add more and would appreciate pull
requests. I only got the very basics working and haven't had time to go
back to it.

Good luck

**Comment by skulumani** [comment]
Closed in a90e1c43b9c4ce623e9ff2bd9f27df17b0a827fe
